// Starting question bank. `answers` lists every accepted spelling.
const QUESTIONS = [
  { question: "Kokia Lietuvos sostinė?", answers: ["Vilnius"] },
  { question: "Kiek žemynų yra Žemėje?", answers: ["7", "septyni"] },
  { question: "Kuri planeta yra arčiausiai Saulės?", answers: ["Merkurijus"] },
  { question: "Kokia ilgiausia Lietuvos upė?", answers: ["Nemunas"] },
  { question: "Kiek kojų turi voras?", answers: ["8", "aštuonias", "aštuonios"] },
  { question: "Kokios spalvos yra vidurinė Lietuvos vėliavos juosta?", answers: ["žalia", "žalios"] },
  { question: "Kuris cheminis elementas žymimas raide O?", answers: ["deguonis"] },
  { question: "Kas parašė poemą „Metai“?", answers: ["Kristijonas Donelaitis", "Donelaitis"] },
  { question: "Koks didžiausias pasaulio vandenynas?", answers: ["Ramusis", "Ramusis vandenynas"] },
  { question: "Kiek dienų turi keliamieji metai?", answers: ["366"] },
  { question: "Kuriais metais Lietuva įstojo į Europos Sąjungą?", answers: ["2004"] },
  { question: "Kokia valiuta buvo Lietuvoje prieš eurą?", answers: ["litas", "litai"] },
  { question: "Koks aukščiausias pasaulio kalnas?", answers: ["Everestas", "Džomolungma"] },
  { question: "Kiek spalvų turi vaivorykštė?", answers: ["7", "septynias", "septynios"] },
  { question: "Kokia programavimo kalba veikia kiekvienoje naršyklėje?", answers: ["JavaScript", "JS"] },
  { question: "Kiek bus 7 × 8?", answers: ["56"] },
  { question: "Kuriame Lietuvos mieste yra didžiausias jūrų uostas?", answers: ["Klaipėda", "Klaipėdoje"] },
  { question: "Kiek kaulų turi suaugusio žmogaus skeletas?", answers: ["206"] },
  { question: "Kuri šalis ribojasi su Lietuva šiaurėje?", answers: ["Latvija"] },
  { question: "Kas nutapė „Moną Lizą“?", answers: ["Leonardo da Vinci", "da Vinci", "Leonardas da Vinčis"] },
  { question: "Kas sukūrė Lietuvos himną „Tautiška giesmė“?", answers: ["Vincas Kudirka", "Kudirka"] },
];
